### ISSUE TITLE
One Click Update .exe not functional

### ISSUE THREAD

**Issue by DeveloperTommy** [Saveyour-Team/Saveyour#10]
There is no "one click update" on the Saveyour.exe.

**Comment by NateFuller** [comment]
@dengitzjg Is this taken care of? I see that you've added this functionality in your "updater" branch. Does anything else need to be done before we can close out this issue?

Edit: I suppose just merging with master is left before closing out?

**Comment by justin-guan** [comment]
I've added an update button in the updater branch, however it's not downloading correctly yet. I would consider this issue still open until I can get it to properly download.

**Comment by NateFuller** [comment]
Sounds good. Keep up the good work!

**Comment by justin-guan** [comment]
Updater has successfully been implemented. There may be some new bugs regarding this new feature, however this issue has been fixed.
