### ISSUE TITLE
Clicking X does not dispose properly

### ISSUE THREAD

**Issue by DeveloperTommy** [Saveyour-Team/Saveyour#14]
When trying to click the X with a Timer running, the program throws an exception and also does not quit. Only pressing "Ok" allows for the program to exit gracefully. Also assigning to @bpteich .

**Comment by bpteich** [comment]
This is no longer an issue in the latest update to Master branch.  The issue was that the Login form was being hidden rather than closed.

**Comment by NateFuller** [comment]
Reopening this.

After closing all the Saveyour windows, the Saveyour.exe process still shows up in Windows Task Manager. How do we get it to actually fully terminate?

**Comment by NateFuller** [comment]
Short-term suggestion: Perhaps closing the "settings" module just exits the program altogether? That could be a temporary fix until we figure something out.

**Comment by NateFuller** [comment]
@bpteich fixed this with commit a308077. Instead of the X button doing this, he added a "Exit Application" button in the Settings Module.
