### ISSUE TITLE
Updater does not update for multiple files

### ISSUE THREAD

**Issue by DeveloperTommy** [Saveyour-Team/Saveyour#15]
Code does not handle update for multiple files yet.

**Comment by justin-guan** [comment]
This issue cannot be dealt with until additional files are added to Saveyour.

**Comment by NateFuller** [comment]
Doesn't need to be fixed because there is only one file that needs to be updated (Saveyour.exe).

This could be reopened if there eventually is more than 1 file that needs to actually get updated. For example, if we provide Saveyour an additional dependency that is NOT SaveyourUpdate.dll.
