### ISSUE TITLE
Maximizing the main module misplaces text

### ISSUE THREAD

**Issue by SenhW** [Saveyour-Team/Saveyour#25]
![capture](https://cloud.githubusercontent.com/assets/8893238/7125796/effd8d42-e201-11e4-8769-3ae22544f3fa.PNG)

**Comment by NateFuller** [comment]
Quickfix here might just be to set ResizeMode="NoResize" for that .xaml file.

**Comment by justin-guan** [comment]
This is no longer a problem. All windows are non resizable except Google Calendar (which auto sizes).
