### ISSUE TITLE
After updating from a previous version, it is impossible to register

### ISSUE THREAD

**Issue by patbeagan1** [Saveyour-Team/Saveyour#30]

**Comment by patbeagan1** [comment]
register is grayed out

**Comment by NateFuller** [comment]
@patbeagan1 Can you provide a screenshot? I'm on mac and unfortunately cannot test out the client myself, so a screenshot of the issue will give me a better idea of the issue to be addressed :)

Thanks!

**Comment by NateFuller** [comment]
This will fixed when we actually update the release branch.

**Comment by justin-guan** [comment]
This has been fixed.
The release repository has been updated to have a proper release for SaveyourUpdater to update to. The new update should have the full functionality of Saveyour that is currently available.
