### ISSUE TITLE
Cloud saving does not seem to be implemented

### ISSUE THREAD

**Issue by DeveloperTommy** [Saveyour-Team/Saveyour#33]
I noticed this issue when we ran into another issue where the application kept crashing and didn't know why when switching to another branch to pull some changes. After debugging through the console and discussing with @dengitzjg, we found out that data wasn't being saved to the database and that the loader loads from local disk only properly.

**Comment by bpteich** [comment]
I just checked by doing calls on the database before and after editing the text in quicknotes, and it is saving the data there.  Maybe the program isn't loading it correctly?

You can ssh in and do:
mongodb
user SaveYourDB
db.SaveYourDB.find({usr : 'Tommy'})

And it'll show Tommy's entry.  Look at the data, edit quicknotes in the client and exit, then do the commands again and look at the data again.

**Comment by DeveloperTommy** [comment]
Oops, forgot to mention that this was on the Weekly To-Do module. So I have some stuff written in for the Weekly To-Do module that @dengitzjg was unable to see (it was a blank module).

**Comment by bpteich** [comment]
In that case it's probably something with how the save() output in WeeklyToDo is formatted, is this the new version?

**Comment by DeveloperTommy** [comment]
Yup, the thing is, I think there were only UI changes in the new version.

**Comment by bpteich** [comment]
The master branch is still saving WeeklyToDo, is that not the new version?

**Comment by DeveloperTommy** [comment]
Oh, no, I'm speaking for the WeeklyToDo branch

**Comment by DeveloperTommy** [comment]
Nevermind, after pulling and merging from master, it seems to be loading properly.
