### ISSUE TITLE
When a module does not exist/is not downloaded, yet the user's file has settings for that module, the program will crash

### ISSUE THREAD

**Issue by DeveloperTommy** [Saveyour-Team/Saveyour#34]
I noticed this issue when attempting to pull changes from WeeklyToDo for UI reformatting. I had settings for Google Calendar that were to be loaded; however, since the Google Calendar module did not exist in that branch, the load() method kept crashing from trying to load a nonexistent module.

**Comment by NateFuller** [comment]
@DeveloperTommy does this still happen?

**Comment by justin-guan** [comment]
Cannot replicate in latest version of Saveyour (version 1.1.0.0)

**Comment by justin-guan** [comment]
This issue appears to no longer occur. I tried editing the save file with invalid modules to load, but nothing happened. Can someone confirm if this is the case for them too?

**Comment by DeveloperTommy** [comment]
Closed. Code has evolved to handle the issue.
