### ISSUE TITLE
Server truncates user data beyond a certain length.

### ISSUE THREAD

**Issue by bpteich** [Saveyour-Team/Saveyour#36]
It appears that the server is truncating user data beyond a certain length.  This only really became noticeable after adding several tasks to WeeklyTodo, but it will end up being pretty important.

**Comment by bpteich** [comment]
Issue was actually client-side.  Network controller was truncating the data to fit a 256 byte buffer.  I increased it to 1MB so any user data under 1MB will be fine.

**Comment by NateFuller** [comment]
Good work :D
![me gusta](https://cloud.githubusercontent.com/assets/4147804/7334591/005f221e-eb66-11e4-977d-f8e0aa016cc6.png)
