### ISSUE TITLE
Google Calendar module opening 3 times on login.

### ISSUE THREAD

**Issue by NateFuller** [Saveyour-Team/Saveyour#37]
### Description

After logging in on the WeeklyToDo branch, 3 instances of the Google Calendar module open.
### Screens

![multiple_cals](https://cloud.githubusercontent.com/assets/4147804/7334576/a2bf80b8-eb65-11e4-855c-b83168af9073.PNG)

**Comment by NateFuller** [comment]
This is actually happening on Master for me as well. No clue why... Giving this high priority

**Comment by DeveloperTommy** [comment]
I believe it's happening in master due to switching from WeeklyToDo because it saves 3 module data. That's why on master it'll open three since the modules are loaded based on saved user data. I think the problem lies in WeeklyToDo. Don't have access to a right now because of the TEDx conference, but I'll try to take a look at it.

**Comment by DeveloperTommy** [comment]
Try creating a new user and logging in with that in master

**Comment by DeveloperTommy** [comment]
Computer\* and later*

**Comment by NateFuller** [comment]
Okay so I create a user, it spawns 1. Log out and log back in, it spawns 2. Keeps doing 2 on repeat logout/login.

Then I create a task in WeeklyToDo, log out, log in, and it spawns 3. Logout/login it keeps spawning 3.

Create another task in WeeklyTodo, log out, log in, and it spawns 4. I think I'm starting to see a pattern. Perhaps on the first time the Google Calendar module is getting loaded before the WeeklyToDo which is making it only spawn on G-Cal on the first?

**Comment by DeveloperTommy** [comment]
Hmm. It might have something to do with the saving and loading logic as well as I suspect there's a bug being spawned in loggedInWindow.xaml where a new Google calendar module is being spawned there.

**Comment by DeveloperTommy** [comment]
Oh, also I think there was a recent merge to master from WeeklyToDo, so the bug might actually be in both those branches.

**Comment by justin-guan** [comment]
I'm not 100% sure on this, but I remember when pressing the left and right buttons on WeeklyToDo, it would cause more Google calendar modules to get created when I logged in the next time. I'm not really available to further test this, but if it is the case, then there might be a problem with the save/load function or the "onLostFocus" event.

**Comment by bpteich** [comment]
We might want to add a check in Shell to ensure only one copy is ever loaded.  I think I did that for some other module at one point.

**Comment by NateFuller** [comment]
It seems that whenever the Weekly Todo module is updated (i.e. a task is added or removed) it will just +1 more instance of it the next time you login.

**Comment by NateFuller** [comment]
@DeveloperTommy fixed this with commit a485403
