### ISSUE TITLE
Custom Windows are not handling right click events and therefore crashing.

### ISSUE THREAD

**Issue by NateFuller** [Saveyour-Team/Saveyour#39]
#### Steps to reproduce
- Open Saveyour.exe.
- Right-click the menu bar area.
- Windows will report that Saveyour has stopped and you must close the application.
- **Optional**: Log into any account and right click the menu bar of any of the custom windows (this does not include the Google Calendar module).
#### Debugging materials
- While in debug mode, VS returns the following information at the time of the exception:

```
An unhandled exception of type 'System.InvalidOperationException' occurred in PresentationFramework.dll
Additional information: Can only call DragMove when primary mouse button is down.
```

This exception is raised when this.DragMove() is called at the following section within LoginWindow.xaml.cs:

```
private void titleBar_MouseDown(object sender, MouseButtonEventArgs e)
{
      this.DragMove();
}
```
#### Screens

![rightclick_crash](https://cloud.githubusercontent.com/assets/4147804/7361093/2c56de90-ed21-11e4-86f9-873cbd59b11e.PNG)

**Comment by justin-guan** [comment]
Added an event handler for right clicks and middle clicks. All mouse clicks are now handled by Saveyour by the title bar. This issue has been resolved.
